### ISSUE TITLE
Syncing Array Fields Values to Google Sheets showing [Ljava.lang.Object;@......]

### ISSUE THREAD

**Issue by Subroid** [grahamearley/FirestoreGoogleAppsScript#100]
## Minimal Code to Reproduce the Problem
```javascript
  const allDocuments = allDocumentsWithMetadata.map(function(documentWithMetadata) {
    const document = documentWithMetadata.obj
    return document;
  });
 
  const firstDocument = allDocuments[0];  
  const columns = Object.keys(firstDocument).sort();
  Logger.log(columns);
  Logger.log(firstDocument);
  const sheet = SpreadsheetApp.getActiveSheet();
  sheet.appendRow(columns);
  
  allDocuments.forEach(function(document) {
    const row = columns.map(function(column) {
      return document[column];
    });
    sheet.appendRow(row);
  });
```

## Explain the Problem in Detail

Firestore Documents have array fields like this
![image](https://user-images.githubusercontent.com/29721105/87240797-692e2300-c43a-11ea-8a06-e305497924b2.png)

But in Google Sheets, getting results like this
![image](https://user-images.githubusercontent.com/29721105/87240817-8f53c300-c43a-11ea-87cb-10edbcbd7145.png)

##### Library Version: 33

**Comment by LaughDonor** [comment]
The column `product_name` is an array, not a string, and the spreadsheet doesn't know how to display the array, which is what you stored in that cell.

How are you expecting the spreadsheet to display multiple values in a single cell?

**Comment by Subroid** [comment]
Yes.  That's what I'm also trying to figure out. Can you guide me?

**Comment by LaughDonor** [comment]
> Yes. That's what I'm also trying to figure out. Can you guide me?

I don't know what to guide you to.
1. Your issue is unrelated to this library.
1. You haven't provided the **results you're trying to expect.**

**Comment by Subroid** [comment]
> > Yes. That's what I'm also trying to figure out. Can you guide me?
> 
> I don't know what to guide you to.
> 
> 1. Your issue is unrelated to this library.
> 2. You haven't provided the **results you're trying to expect.**

I want product name array values to be appeared into one cell and separated by pipe

**Comment by LaughDonor** [comment]
Here's your [hint](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join). 

Please use [StackOverflow](https://stackoverflow.com/) for other questions as these issues are not related to this library.
