### ISSUE TITLE
updateDocument() method give error "lacks a collection id at index 55"

### ISSUE THREAD

**Issue by Subroid** [grahamearley/FirestoreGoogleAppsScript#101]
## Minimal Code to Reproduce the Problem
```javascript
const firestore = FirestoreApp.getFirestore(email, key, projectId);
Logger.log(productsCollPath+'/'+dataToExport['product_id'])
 firestore.updateDocument(
    productsCollPath+'/'+dataToExport['product_id'], dataToExport);    
  

```

## Explain the Problem in Detail

**Here's the log for document path I want to update**

![image](https://user-images.githubusercontent.com/29721105/87867526-650a8400-c9ab-11ea-9739-fd6019197240.png)

**And this path exists**

![image](https://user-images.githubusercontent.com/29721105/87867564-c4689400-c9ab-11ea-848c-5d4080db8b9d.png)

##### Library Version: 33

**Comment by LaughDonor** [comment]
I don't see the value of `productsCollPath` in your question, it's cut off.

**Comment by Subroid** [comment]
> I don't see the value of `productsCollPath` in your question, it's cut off.
> 
> Make sure that `productsCollPath` starts with "FreshFastStoresMain/”.


**Here's the complete log for document path I want to update**

![image](https://user-images.githubusercontent.com/29721105/87868432-11039d80-c9b3-11ea-80b1-c1f7ee45bf40.png)

**And here's the same path in firestore which exists**

![image](https://user-images.githubusercontent.com/29721105/87868450-3bedf180-c9b3-11ea-9fb6-876a582132f2.png)

**Comment by LaughDonor** [comment]
Emphasis on ”cut off", not hidden. What does the variable `productsCollPath` start with?

**Comment by Subroid** [comment]
Here's the value of `productsCollPath` 

![image](https://user-images.githubusercontent.com/29721105/87869463-b7ed3700-c9bd-11ea-9c18-b15b6b05d661.png)

**Comment by Subroid** [comment]
> I don't see the value of `productsCollPath` in your question, it's cut off.
> 
> Make sure that `productsCollPath` starts with "FreshFastStoresMain/”.

Now I got it fixed. You are right. Actually I added '/' before "FreshFastStoresMain". Removing it fixed the issue. Thank you so much.
