### ISSUE TITLE
Google Apps Script: Missing ; before statement.

### ISSUE THREAD

**Issue by nathgilson** [grahamearley/FirestoreGoogleAppsScript#104]
## Expected Behavior
Extension opens as expected

## Actual Results
Extension doesnt appear in the menu, and error in the console: "Google Apps Script: Missing ; before statement."

##### Library Version: 
33 with Rhino ("DEPRECATED_ES5")

**Comment by LaughDonor** [comment]
As stated in the README:

> Scripts utilizing the old Rhino runtime must use v26.

**Comment by nathgilson** [comment]
@LaughDonor it works but now I keep getting the "Google Apps Script: You do not have permission to call UrlFetchApp.fetch" error

**Comment by LaughDonor** [comment]
@nathgilson Are you running Firestore functions in a Trigger?

**Comment by nathgilson** [comment]
No I don't

**Comment by LaughDonor** [comment]
What did you mean by "Extension doesnt appear in the menu"? Which menu should it be appearing in?

**Comment by nathgilson** [comment]
My extension doesn't appear in the Add-on menu. Instead I get this error (see screenshot):

<img width="1440" alt="Screenshot 2020-09-11 at 18 23 03" src="https://user-images.githubusercontent.com/28766479/92949717-d884bb00-f45b-11ea-81f1-00a488466381.png">

**Comment by nathgilson** [comment]
**I found a patch: you have to call firestore as a funstion:**
const firestore = () => FirestoreApp.getFirestore(client_email, private_key, project_id)
const userDoc = firestore().getDocument(`user`)
...

instead of:
const firestore = FirestoreApp.getFirestore(client_email, private_key, project_id)
const userDoc = firestore.getDocument(`user`)
...

**Comment by LaughDonor** [comment]
This is not an Add-on. It's a library for Google Apps Script. You have to create your own add-on and utilize this library to connect to your specific database and interact with it.

**Comment by nathgilson** [comment]
i know i was talking about my own add-on of course

**Comment by LaughDonor** [comment]
You still need to execute your function at least once within Google Apps Script so that you can authorize Google to utilize the necessary permissions.
