### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mariaanasb** [grahamearley/FirestoreGoogleAppsScript#105]
Hello,

I have this error when I try to import from firebase.

**TypeError: Cannot convert undefined or null to object**

I also followed this video: https://www.youtube.com/watch?v=TD3kWcb2TH0

The line which is giving me troube is this one:
  //3. Get the first document from a collection
  const first = allDocuments[0];
  const columns = Object.keys(first);

Can anyone help me?

Thank you

**Comment by LaughDonor** [comment]
1. That video (which is cool!) is using an older version of this library, which has some deprecated features (and runs on old Rhino engine. Please follow the instructions in the Readme for getting a document when using the latest version.
_Hint:_ Use `first.obj`

2. Do you have data in the collection you are querying?

**Comment by mariaanasb** [comment]
Hello @LaughDonor !

1. I did that, which basically changed nothing. 
I just tried `first.obj` but where do they `keys `get in?

2. I do! lots

**Comment by mariaanasb** [comment]
hello again @LaughDonor 

I changed to v26 and it worked :)
fastest way I guess

thank you for your help!

**Comment by LaughDonor** [comment]
> 1. I did that, which basically changed nothing.
>    I just tried `first.obj` but where do they `keys `get in?

You should be able to set breakpoints in your code when you run it (click in the left margin of the code space where you want to set) and grab the variable values at that point of execution. What values do you get?

> I changed to v26 and it worked :)
> fastest way I guess

You shouldn't need to resort to using an older version to get things working. I'm hoping you're able to get things going with the latest version.
