### ISSUE TITLE
How to query by timestamp

### ISSUE THREAD

**Issue by danieleorlando** [grahamearley/FirestoreGoogleAppsScript#108]
How to query a collection by a timestamp field?

I tried so many combinations that I can't figure it out

**Comment by LaughDonor** [comment]
Is it an actual field, or the metadata? We cannot query on the meta data, whereas we can query the field values.

**Comment by danieleorlando** [comment]
It's a field

**Comment by LaughDonor** [comment]
Can you provide an example query you utilized to get this information as well as the Library version number?

**Comment by danieleorlando** [comment]
I'm using version 26

`
const allDocuments = firestore.query(collection).where(field, ">=", date).execute();  
`

I tried date like
date = new Date()
date = new Date("2020-01-01")

Probably I don't know how to format date 

`where("name", "==", name).execute();  
` this works perfectly

**Comment by danieleorlando** [comment]
Updated to v33. Now query by timestamp works perfectly
