### ISSUE TITLE
Setting document reference as a field

### ISSUE THREAD

**Issue by ShreeniwasIyer** [grahamearley/FirestoreGoogleAppsScript#109]
## Explain the Problem in Detail
I have two sheets - one containing "tips" and the other referring to the tips through an id. When I write this to firestore, I want tips to be in a separate collection and questions to be in a separate collection with a reference field to the corresponding tip document. 

The current library allows me to only put the field as a string (where I have tried sending in the full document url, or relative document URL), but it is set as a string and not as a document reference. Does anyone know how to set reference fields in the current API?

##### Library Version:

**Comment by LaughDonor** [comment]
I guess it's not better documented. Reference values must take on the format of:
```
projects/my-project-name/databases/(default)/documents/my-collection-name/my-document-name/my-optional-subcollection/my-optional-subdocument
```

Where all the `my-*` sections of the path should be replaced.

**Comment by ShreeniwasIyer** [comment]
That worked! Thank you.
