### ISSUE TITLE
ReferenceError: FirestoreApp is not defined

### ISSUE THREAD

**Issue by Paul25995** [grahamearley/FirestoreGoogleAppsScript#110]
## Minimal Code to Reproduce the Problem
javascript (Google Apps Script)
```
function getFirstDocuments() {
  var email = "ausbildungsnachweis-72890@appspot.gserviceaccount.com";
  var key = "-----BEGIN PRIVATE KEY-----\PRIVATE KEY\n-----END PRIVATE KEY-----\n";
  var projectId = "ausbildungsnachweis-72890";
  const firestore = FirestoreApp.getFirestore(email, key, projectId);
  
  const allDocuments = firestore.getDocuments("PaulKoplin");
  console.log(allDocuments);
}
```

## Explain the Problem in Detail
If I run the Code, I get the following Issue:
ReferenceError: FirestoreApp is not defined

##### Library Version: 30
(I have also try to run the Code with Library Version: 11)

**Comment by LaughDonor** [comment]
I don't see `firebase` in your code.

**Comment by youleaf** [comment]
I hope you obfuscated your private key above. In case you didn't, I recommend you to change it asap.

**Comment by LaughDonor** [comment]
> I hope you obfuscated your private key above. In case you didn't, I recommend you to change it asap.

The private key in OP is too short :) I think he's good.

**Comment by Paul25995** [comment]
> I don't see `firebase` in your code.

What do you mean?

**Comment by LaughDonor** [comment]
> > I don't see `firebase` in your code.
> 
> What do you mean?

Well you updated the post from `firebase` to `FirestoreApp`.

Anyway, can you post a screenshot of your Referenced Libraries dialog box?

**Comment by Paul25995** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/53189877/98426468-3b2fb700-2099-11eb-99e2-ebd05a9f9b6b.png)

**Comment by Paul25995** [comment]
> > > I don't see `firebase` in your code.
> > 
> > 
> > What do you mean?
> 
> Well you updated the post from `firebase` to `FirestoreApp`.
> 
> Anyway, can you post a screenshot of your Referenced Libraries dialog box?

I saw it after I already answered, so I updated it

**Comment by LaughDonor** [comment]
Resources -> Libraries menu
![image](https://user-images.githubusercontent.com/168200/98427123-731b0800-2061-11eb-8006-4d41a989c356.png)
 something like this.. in fact, it should look exactly like this... including any other libraries you have.

**Comment by Paul25995** [comment]
I made a mistake during import
