### ISSUE TITLE
Group Collection

### ISSUE THREAD

**Issue by halahmadi** [grahamearley/FirestoreGoogleAppsScript#114]
Thank you for this amazing work. I would love to see the feature group collection query. It simplifies so much complexity.

**Comment by ribrdb** [comment]
I'm using this:

```js
function collectionGroup(firestore, id) {
  const query = firestore.query();
  query.from=[{collectionId:id, allDescendants: true}];
  return query;
}
```

**Comment by LaughDonor** [comment]
Are you referring to grabbing all nested documents, @halahmadi? You should be able to loop through the nested collections yourself.

**Comment by ronykrell** [comment]
Think it's something like this
https://firebase.googleblog.com/2019/06/understanding-collection-group-queries.html
