### ISSUE TITLE
Update throws "Error: Document already exists"

### ISSUE THREAD

**Issue by cyaconi** [grahamearley/FirestoreGoogleAppsScript#116]
## Minimal code to reproduce the problem
```javascript
const firestore = FirestoreApp.getFirestore(email, key, projectId);
const collection = "MyCollection";
firestore.updateDocument(collection+"/"+doc.id, doc);
```

## Expected Behavior
When I try to update an existing document, I expect the document identified by `doc.id` gets updated on the DB.

## Actual Results
Library throws `"Error: Document already exists"`

```
Error: Document already exists: projects/myproject-123456/databases/(default)/documents/MyCollection/be74535d4d67570a3570da220f8e17e4
checkForError	@ Request.gs:135
method_	@ Request.gs:50
patch	@ Request.gs:108
updateDocument_	@ FirestoreWrite.gs:47
createDocument_	@ FirestoreWrite.gs:21
createDocument	@ Firestore.gs:83
```

##### Library Version: 33

**Comment by LaughDonor** [comment]
Is `doc.id == 'be74535d4d67570a3570da220f8e17e4'`? If not, what is the value of `doc.id`?

**Comment by cyaconi** [comment]
Exactly, `doc.id` is `'be74535d4d67570a3570da220f8e17e4'`

**Comment by LaughDonor** [comment]
I feel like there's something else here at play, because this scenario passes the exact UnitTest [here](https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/3870b5a64ee323863aabbe5e68e2a2b08481c1a7/Tests.ts#L128-L142) which is live.

Can you provide any more details? Does this happen with every document you try to update?

**Comment by cyaconi** [comment]
After digging into my code, I found a naive mistake. 
I can confirm the updateDocument method it's working as excepted, my apologies. I'm closing the issue.
