### ISSUE TITLE
Firestore query does not accept "!=" operator

### ISSUE THREAD

**Issue by cayeborreo** [grahamearley/FirestoreGoogleAppsScript#117]
## Minimal code to reproduce the problem
```js
const firestore = FirestoreApp.getFirestore(email, key, projectId);
const allData = firestore.query("table")
    .Where("availability", "!=", "")
    .Execute();
Logger.log(allData);
```

## Expected Behavior
- Return user documents that fulfill query - ie exclude documents where the `availability` field is null

## Actual Results
![image](https://user-images.githubusercontent.com/39559163/110570192-81ed0500-8190-11eb-8ac5-a796eeab25c1.png)

##### Library Version: 
33

**Comment by LaughDonor** [comment]
We just try to translate the original API, and the `!=` and `not null` are not part of the spec.

I was going to suggest that you try the `> ""` approach, but seems like you found it!
