### ISSUE TITLE
Error: Missing or insufficient permissions

### ISSUE THREAD

**Issue by daniyalas** [grahamearley/FirestoreGoogleAppsScript#119]
![image](https://user-images.githubusercontent.com/50423149/113415473-b727f400-93d8-11eb-9ebb-607acfb5f500.png)

Why am I getting this error

`Error: Missing or insufficient permissions.`

`checkForError	@ Request.gs:135`

`method_	@ Request.gs:50`

`get	@ Request.gs:82`

`getDocument_	@ FirestoreRead.gs:74`

`getDocument	@ Firestore.gs:44`

P.S. I am trying to read/get the data and I have Viewership access to the database.

**Comment by LaughDonor** [comment]
@daniyalas Did you get to resolve this issue? It doesn't seem like a library issue.

**Comment by daniyalas** [comment]
It did get resolved but I am sorry I don't remember how.

**Comment by madeupofstardust** [comment]
Hello. I had the same problem.

![image](https://user-images.githubusercontent.com/91166153/138158863-31a3a64a-0085-4e26-b6c7-a80e6ec44a1e.png)

I had a "firestore.gs" file for my configuration, when I renamed it, it worked. Then I changed back to firestore.gs, and still worked. It was very strange. I hope this works for someone else.
