### ISSUE TITLE
creating document with date field using servertime

### ISSUE THREAD

**Issue by rrrepos** [grahamearley/FirestoreGoogleAppsScript#127]
I  am updating documents from Google Sheets to my Firestore database

## Minimal Code to Reproduce the Problem
```javascript
...
const firestore = FirestoreApp.getFirestore(email, key, projectId);
...
var ss = SpreadsheetApp.getActiveSpreadsheet();
var sheets = ss.getSheets();
var sheet = ss.getActiveSheet();
var data = sheet.getDataRange().getValues();
...
... 
for (i = 1; i < data.length; i++) {
  var field1 = data[i][0];
  var field2 = data[i][1];
  ..
  const json = {
        'f1' : field1,
        'f2': field2,
        'createdOn': FieldValue.serverTimestamp() // this gives an error
      }
      firestore.createDocument('collection/', json);
}
...

```

## Explain the Problem in Detail
Is it possible to set a field using the Server Time Stamp?

##### Library Version: 
33

Thanks

**Comment by LaughDonor** [comment]
What is `FieldValue` a reference to? Is there something wrong with `'createdOn': new Date()`?

**Comment by rrrepos** [comment]
Thanks for the response. The thought was to use server time. Hence the use of `serverTimeStamp` in place of `new Date()`. I am using it in the manner you have suggested.
