### ISSUE TITLE
getDocuments doesn't retrieve timestamp data

### ISSUE THREAD

**Issue by soitecOpensources** [grahamearley/FirestoreGoogleAppsScript#13]

**Comment by grahamearley** [comment]
Thanks for pointing this out — this is an issue specifically with the latest versions. I neglected to include all the document data in the return of the `getDocuments` function. It only returns the fields.

I'll add the timestamps back in soon, but in the meantime **here's a workaround** using the older version of the library:

If you use [Version 8](https://script.google.com/macros/library/d/1VUSl4b1r1eoNcRWotZM3e87ygkxvXltOgyDZhixqncz9lQ3MjfT1iKFw/8), the `get` function (when given a document path) will return all the document information, including its timestamp data and fields. The fields will be typed (e.g. a mapping to a string `name: "Name"` will show up in the object as `name: { stringValue: "Name" } `. 

To unwrap the value `document` you get from calling `FirestoreApp.get("your/document/path/here", email, key, projectid)`, call `FirestoreApp.getFieldsFromFirestoreDocument(document)`.

**Comment by grahamearley** [comment]
@soitecOpensources In the latest library version ([15](https://script.google.com/macros/library/d/1VUSl4b1r1eoNcRWotZM3e87ygkxvXltOgyDZhixqncz9lQ3MjfT1iKFw/15)), that functionality is now available! Added in this commit: eceb6deebca9acb22d64867a934387b664d8ad41

**Comment by LaughDonor** [comment]
I'm still not seeing timestamp data. That field returns `null` when using `getDocuments()`.

**Comment by LaughDonor** [comment]
@grahamearley Sorry, I meant the field timestamp typed data was not showing.

**Comment by grahamearley** [comment]
@LaughDonor Oh, I see what you're saying. Yes, there are still some unimplemented data types. I'll file an issue for getting those implemented.
