### ISSUE TITLE
Is it possible to add Google Sheets data as an array field in Firestore?

### ISSUE THREAD

**Issue by tom-alder** [grahamearley/FirestoreGoogleAppsScript#133]
## Explain the Problem in Detail

Is it possible to add data in Google Sheets as an array field-type in Firestore?

In the Firestore docs, it has an example of how to write an array data type: https://cloud.google.com/firestore/docs/manage-data/add-data

`const docData = {
    arrayExample: [5, true, "hello"],
};` 

If I have a cell with data 
`[5, true, "hello"]`
is it possible for me to store that as an array in Firestore?

I have seen that a similar request around *appending* to a Firestore array field was marked as invalid due to REST API limitations: https://github.com/grahamearley/FirestoreGoogleAppsScript/issues/78

Wondering if this may be impossible for a similar reason?

Thanks!

**Comment by LaughDonor** [comment]
Sorry for checking this out late, @tom-alder.

This sounds like an implementation detail when utilizing this library. You wouldn't be able to _directly_ take the contents of a cell and push it to Firebase, or it'll just store it as a string. You'll want to convert those values into an array yourself before pushing it to Firebase.
