### ISSUE TITLE
URL has not been whitelisted in the script manifest.

### ISSUE THREAD

**Issue by Shivani12345** [grahamearley/FirestoreGoogleAppsScript#135]
I neet to send data from googlesheet from drive addon to firestore database  but I am getting error like :
Exception: Request to https://oauth2.googleapis.com/token failed because the URL has not been whitelisted in the script manifest.

**Comment by LaughDonor** [comment]
This isn't an issue with the library. Did you check out https://developers.google.com/apps-script/manifest/allowlist-url ?
