### ISSUE TITLE
firestore.getDocuments("customers") throws error: "SyntaxError: Unexpected end of JSON input" 

### ISSUE THREAD

**Issue by WillTisdale** [grahamearley/FirestoreGoogleAppsScript#136]
## Minimal Code to Reproduce the Problem
```javascript
//My email, key, and projectId are correct because I am successful when pulling other collections
const firestore = FirestoreApp.getFirestore(email, key, projectId);
const allDocuments = firestore.getDocuments("customers")
//OR
const allDocuments = firestore.query("customers").Execute()
```

## Explain the Problem in Detail

1. I expect to get all documents ordered by their Firestore ID
2. I get an error: "SyntaxError: Unexpected end of JSON input" 
3. The code above works if I use either of the following lines:

```javascript
//It only works if I use OrderBy but this filters out many customers if they don't have the field I am ordering by
const allDocuments = firestore.query("customers").OrderBy("email").Execute()
//Teams is a much smaller collection and it works
const allDocuments = firestore.getDocuments("teams")
```

4.  Is it possible that some of my documents in the "customers" collection does not have an ID because from my understanding it orders by ID on default?
5.  Is it possible that after the return of all documents there is a field that is causing a JSON syntax error?

I have every possible field type on my customer documents (boolean, string, map, array, geopoint, number) 

There are 80,000 customers. I have tried pulling one with the following method:

```javascript
const allDocuments = firestore.getDocument("customers/customerId")
```
I go into the database and edit the customer to try and break a single one and I cannot pinpoint how one is being broken.
- I've added a field name with a space ("Test Field").
- I tried pulling a customer with a stringified JSON object in a String field
- I tried pulling a customer with no fields
- Everything I have tried and I cannot pull one and get the same error but when I try to get all customers I get the error: "SyntaxError: Unexpected end of JSON input"

### Other Comments
I have successfully pulled all customers with node.js and swift syntax for months and now am trying to add data to google sheets and running into this issue.

##### Library Version: 
I am using FirestoreApp version 33 in Google AppScript for Google Sheets when I get the error

**Comment by WillTisdale** [comment]
I found a work around was to use the function getDocumentIds("customers") and then I am able to loop through each Id and use the function getDocument("customers/customerID"). Still not sure why I cannot use getDocuments("customers") without receiving the "SyntaxError: Unexpected end of JSON input". If it helps to determine, here is the specific files and lines where the errors were coming from.

```javascript
SyntaxError: Unexpected end of JSON input
method_	@ Request.gs:49
post	@ Request.gs:95
callback	@ FirestoreRead.gs:115
Execute	@ Query.gs:241
getDocuments	@ Firestore.gs:56
```

**Comment by LaughDonor** [comment]
That error usually comes from some error with the data. Since it fetches all the documents, it may be hitting some type of data limit based on your feedback (JSON response is too large and the JSON parser doesn't capture the closing characters).

I suggest you use a form of `firebase.query("customers").Limit(100).Offset(200).Execute();` to fetch your data in batches.

**Comment by WillTisdale** [comment]
That makes sense. I have over 7000 customers with data I am trying to pull and it must just be too much data. I will use your advice and create a dynamic offset to get 100 items at a time. Thanks for the response.
