### ISSUE TITLE
Key error on query

### ISSUE THREAD

**Issue by riverscuomo** [grahamearley/FirestoreGoogleAppsScript#140]
## Minimal code to reproduce the problem
```javascript
const firestore = FirestoreApp.getFirestore(email, key, projectId);
const allDocuments = firestore.query("anyQueryHere")
```

## Expected Behavior
I've been running this script successfully for a year . Firestore initialization still works.

## Actual Results
But starting today, when I try the query, I get this error.
```
Exception: Invalid argument: key
get createJwt_	@ Auth.gs:39
get options_	@ Auth.gs:61
get accessToken	@ Auth.gs:28
get authToken	@ Firestore.gs:34
query	@ Firestore.gs:116
```
I may have messed up something in Firebase yesterday. So I went ahead and created a new Service account and downloaded a new key.

##### Library Version: 
33

**Comment by grahamearley** [comment]
> I went ahead and created a new Service account and downloaded a new key.

Did this have any impact on the issue? Nothing has changed for the past year or so in the repo, so I think this must be a configuration issue. Any idea what you might have messed up in Firebase?

**Comment by riverscuomo** [comment]
Thanks for the response. I'll close this now because when I hard code the `serviceEmail`, `private_key`, and `project_id `into my script it works fine. There must be some problem with Script Properties (even though they have the same 3 values.)

> Any idea what you might have messed up in Firebase?

I accidentally deleted an Android app in the same project. I guess that wouldn't have any effect on this Google Apps Script.

**Comment by grahamearley** [comment]
Interesting... Well feel free to re-open if you still have issues. Also Weezer rocks.

**Comment by riverscuomo** [comment]
Awesome. This library rocks.

I've been having other problems with Google Apps Scripts in the last 24 hours. Namely, they suddenly haven't been able to find some of my functions and I've had to move them around in the Files browser panel. I'll let you know if I learn anything.

**Comment by jamesarosen** [comment]
[`Utilities.computeRsaSha256Signature`](https://developers.google.com/apps-script/reference/utilities/utilities#computeRsaSha256Signature(String,String)) requires that the `key` be a valid PEM string. That is, it should look like
```
"-----BEGIN PRIVATE KEY-----
privatekeyhere
-----END PRIVATE KEY-----
"

> There must be some problem with Script Properties

I think you're on the right track with this. It seems like the `key` you're getting is not a PEM (and very possibly null/undefined).

**Comment by 3zzy** [comment]
<img width="1975" alt="Screen Shot 2022-09-04 at 10 35 30 am" src="https://user-images.githubusercontent.com/105034/188292243-58a4d980-77de-498a-bc3a-cafd2787ea63.png">

I'm having the same issue although I can log the key fine. 🤔

**Comment by 3zzy** [comment]
This seems to resolve the issue:
`props.getProperty('private_key').replace(/\\n/g, '\n')`

... but not sure if this is the best way to fix it.🤷

**Comment by elmarti** [comment]
@3zzy @riverscuomo  Say it ain't so! It seems the script properties escapes the field input, I got around this by storing the whole service account JSON object as a property i.e:
```
const jsonKey = JSON.parse(PropertiesService.getScriptProperties().getProperty("service_account"));
const key = jsonKey.private_key;
const clientEmail = jsonKey.client_email;  
```

**Comment by epistemologist** [comment]
> <img alt="Screen Shot 2022-09-04 at 10 35 30 am" width="1975" src="https://user-images.githubusercontent.com/105034/188292243-58a4d980-77de-498a-bc3a-cafd2787ea63.png">
> 
> I'm having the same issue although I can log the key fine. thinking

This is easily enough information to fully recover the private key - see [this post](https://blog.cryptohack.org/twitter-secrets) for an example. I highly recommend changing the image to something else.

**Comment by 3zzy** [comment]
Doesn’t help when you quote ;)

I’ll just regenerate the key.

**Comment by LaughDonor** [comment]
As listed in the [Configuration Template](https://github.com/grahamearley/FirestoreGoogleAppsScript#configuration-template), you should ensure your key matches the format literally.

I figure adding some validation to check this would help the adoption rate of this library.

**Comment by glenvollmer** [comment]
thank you Rivers!
