### ISSUE TITLE
Is there anyway to update a nested field but leave other fields unchanged?

### ISSUE THREAD

**Issue by zhezhang77** [grahamearley/FirestoreGoogleAppsScript#145]
## Minimal Code to Reproduce the Problem
```javascript
const firestore = FirestoreApp.getFirestore(email, key, projected);

var ObjA= {
  field1: 'value1',
  field2: {
    field2_1: 'value2_1',
    field2_2: 'value2_2',
  },
};

var ObjUpdate= {
   field2: {
    field2_1: 'value2_1_new',
  },
}

firestore .createDocument('TEST/TEST', ObjA);
firestore .updateDocument('TEST/TEST', ObjUpdate, true);
//firestore .updateDocument('TEST/TEST', ObjUpdate, ['field2']);
//firestore .updateDocument('TEST/TEST', ObjUpdate, ['field2.field2_1']);
```

## Explain the Problem in Detail

I have an object 'ObjA' which has nested fields.
I would like to update the value of its nested fields 'field2_1' but keep other fields unchanged.

Expect Result:
```javascript
var Result = {
  field1: 'value1',
  field2: {
    field2_1: 'value2_1_new',
    field2_2: 'value2_2',
  },
};
```
Actual Result:
```javascript
var Result = {
  field1: 'value1',
  field2: {
    field2_1: 'value2_1_new',
  },
};
```
I tried several ways to set the parameter 'mask' but still the same.
Does anyone know how to get it work?

##### Library Version: v33

**Comment by LaughDonor** [comment]
Unfortunately no. This isn't a feature of the [Cloud Firestore API](https://firebase.google.com/docs/firestore/reference/rest/), so we are unable to leverage that. You would have to either set field2 into a collection, or pull the whole document and update just that field manually.
