### ISSUE TITLE
getDocuments(pathToCollection) does not return the document id as part of the document fields

### ISSUE THREAD

**Issue by chenlevy** [grahamearley/FirestoreGoogleAppsScript#15]
I think it's really important to return the document id as field when getting all the documents from a collection.

**Comment by grahamearley** [comment]
@chenlevy This functionality is added in [version 15](https://script.google.com/macros/library/d/1VUSl4b1r1eoNcRWotZM3e87ygkxvXltOgyDZhixqncz9lQ3MjfT1iKFw/15), from commit eceb6deebca9acb22d64867a934387b664d8ad41. Getting documents in this version will now return an object with metadata — document fields can be accessed by getting the `fields` field in a document object. One of the metadata fields is `name` which will return the path of the document. The ID can be retrieved from the path.
