### ISSUE TITLE
getDocuments() doesn't return the path of each document

### ISSUE THREAD

**Issue by hourback** [grahamearley/FirestoreGoogleAppsScript#154]
Hello!  And thank you for contributing this library!  :-)

This is my first Firestore app.  I'm using Google Apps Script.

I'm still in the process of wiring everything up and learning about the returned values of things and how to manipulate Firestore documents.

I'm using getDocuments() to return a list of documents in my top-level collection.  I'm confused, though, as to why it doesn't return the path of the document but instead the entire, project-level path (if that's an accurate term), which includes not just the document name and parent collection but everything above it, going all the way up to my GCP (Google Cloud Platform) project name.  That would be fine but it appears that I am not permitted to delete a document using this format, i.e., the entire document path going all the way up to GCP.  

Is there another way for me to get the path I can use to delete the document without parsing the full path for each document returned in the result in order to obtain the path segments necessary to pass to deleteDocument()?

##### Library Version:  33

**Comment by LaughDonor** [comment]
Hi @hourback, the absolute path is stripped by the library for ease of use. If you want the full path, just add it back in with your configuration, or strip it out when you want to delete.
