### ISSUE TITLE
FieldValue support

### ISSUE THREAD

**Issue by risalfajar** [grahamearley/FirestoreGoogleAppsScript#163]
Is there any plan to support [FieldValue](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FieldValue)?

It's sentinel values that can be used when writing document fields with `set()` or `update()`:
[isEqual](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FieldValue#isequal)
[arrayRemove](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FieldValue#arrayremove)
[arrayUnion](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FieldValue#arrayunion)
[delete](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FieldValue#delete)
[increment](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FieldValue#increment)
[serverTimestamp](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FieldValue#servertimestamp)

**Comment by LaughDonor** [comment]
That's the Javascript API, this library is interfaces with Firestore using the [REST API](https://firebase.google.com/docs/firestore/reference/rest).

**Comment by risalfajar** [comment]
So you mean this is impossible to support?

**Comment by risalfajar** [comment]
Someone said it's possible to do in this [SO Answer](https://stackoverflow.com/a/59419468/5187873)

**Comment by LaughDonor** [comment]
Interesting, I never noticed the Transforms parameter. I guess it is possible, but not implemented in this Library.

**Comment by risalfajar** [comment]
"Not yet" :)
Could you reopen the issue please? So that this can be implemented in the future.

**Comment by LaughDonor** [comment]
Could you open a new issue that refers to this in the REST API instead of the JS API like you have linked?

**Comment by risalfajar** [comment]
Opened in #164, thanks!
