### ISSUE TITLE
Invalid argument: key

### ISSUE THREAD

**Issue by ranavaibhavgit** [grahamearley/FirestoreGoogleAppsScript#172]
## Minimal code to reproduce the problem
```javascript
function myFunction() {
  const props = PropertiesService.getScriptProperties(); // Or .getScriptProperties() if stored in Script Properties
  const [email, key, projectId] = [props.getProperty('client_email'), props.getProperty('private_key'), props.getProperty('project_id')];
  const firestore = FirestoreApp.getFirestore(email, key, projectId);

  const data = {
    "name": "test"
  }

  firestore.createDocument("FirstCollection", data)

  //const documentWithMetadata = firestore.getDocument("family-check-ins/9999/checkIns");
  //console.log(documentWithMetadata)
}
```

## Expected Behavior
document created

## Actual Results
Exception: Invalid argument: key
get createJwt_	@ Auth.gs:39
get options_	@ Auth.gs:61
get accessToken	@ Auth.gs:28
get authToken	@ Firestore.gs:34
createDocument	@ Firestore.gs:82
myFunction	@ Code.gs:14

##### Library Version: 
33

**Comment by felixbuilds** [comment]
If you are using the PropertiesService to store the private key (with included new-line characters \n, then you must convert the \n characters in the key to the symbolic new-line character as shown in the snippet below:

`var PRIVATE_KEY = PropertiesService.getScriptProperties().getProperty('private_key').replace(/\\n/g, '\n');`

Notice the regular expression at the end to globally replace the characters \n into a valid new-line character.

After converting the \n character sequence to the symbolic newline character, the Utilities.computeRsaSha256Signature method was finally able to correctly generate the signature.

Ran into the same issues with other libraries. Credit to @jpvanoosten for figuring this out.
