### ISSUE TITLE
Add support for all data types

### ISSUE THREAD

**Issue by grahamearley** [grahamearley/FirestoreGoogleAppsScript#18]
The library currently only supports strings, numbers, nulls, lists, and maps. There are other data types possible (like timestamps or references to other documents). Implement these!

See [here](https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/master/FirestoreDocument.js#L65) for where this should be implemented.

**Comment by LaughDonor** [comment]
I think this can be closed now. :)
