### ISSUE TITLE
Can't add your library

### ISSUE THREAD

**Issue by narley** [grahamearley/FirestoreGoogleAppsScript#2]
Hi there,
I tried to add your library to my script and this is what I get:

"You do not have access to library FirestoreApp, used by your script, or it has been deleted."

Would be able to check that?

Cheers!

**Comment by grahamearley** [comment]
Good call! My bad, I hadn't opened up the permissions -- but it should work now. Let me know if it does!

**Comment by narley** [comment]
Thanks. Manage to add now.
