### ISSUE TITLE
Consolidate Calls to Firebase API

### ISSUE THREAD

**Issue by LaughDonor** [grahamearley/FirestoreGoogleAppsScript#22]
To reduce code multiplicity, we should create a base function with common code from calling the API to reduce chances of error if the calls need to be updated.

Functions that are currently making these calls:
- Read.`getPage_` https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/81989e0413a0736bdb5363dc4a085aa8c54a2ce2/Read.js#L19-L35
 - Delete.`deleteDocument_` https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/81989e0413a0736bdb5363dc4a085aa8c54a2ce2/Delete.js#L10-L22
 - Write.`createDocumentWithId_` https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/81989e0413a0736bdb5363dc4a085aa8c54a2ce2/Write.js#L11-L33
- Write.`updateDocument_` https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/81989e0413a0736bdb5363dc4a085aa8c54a2ce2/Write.js#L57-L73
- The upcoming Query.`query_` https://github.com/thesandlord/FirestoreGoogleAppsScript/blob/f861f08daec96bbbc069c56ba882c3e6858dbfff/Query.js#L31-L51

**Comment by grahamearley** [comment]
Implemented in [v16](https://github.com/grahamearley/FirestoreGoogleAppsScript/releases/tag/v16)!
