### ISSUE TITLE
Library Versions do not correspond to Code Release Tags

### ISSUE THREAD

**Issue by LaughDonor** [grahamearley/FirestoreGoogleAppsScript#27]
It would be great if we could have the GitHub repo filled with the 15 (soon to be 16) versions that have been released as tagged versions.

@grahamearley please make this possible so anyone can checkout previous versions as necessary from the times they were released!

Thanks!

**Comment by grahamearley** [comment]
I agree! I've been meaning to make Github releases for library releases. I'll put this on my to-do list.

**Comment by grahamearley** [comment]
Done! Here are the releases: https://github.com/grahamearley/FirestoreGoogleAppsScript/releases

I went back and tagged old releases. For new releases, I'll add a description with notes.
