### ISSUE TITLE
Adding support for undefined field in query

### ISSUE THREAD

**Issue by rcanu** [grahamearley/FirestoreGoogleAppsScript#32]
Thanks for the awesome code @grahamearley 

Can we add support for `undefined` fields in the query?

This is how it will be called:

`
FirestoreApp.getFirestore(SERVICE_ACCOUNT, PRIVATE_KEY, PROJECT_ID)
  .query("/path/to/collection").where("field", "==", undefined).execute()
`

**Comment by rcanu** [comment]
Thanks @LaughDonor for the swift response!

Found out it's **not possible** to query for **undefined fields**
https://stackoverflow.com/questions/49761295/firestore-how-to-query-for-non-existing-undefined-fields

Having this query will work if I will have a **marker value** set in place
`FirestoreApp.getFirestore(SERVICE_ACCOUNT, PRIVATE_KEY, PROJECT_ID) .query("/path/to/collection").where("field", "null").execute()`

So yeah I think I might have to put a marker instead.

Thanks!

**Comment by LaughDonor** [comment]
Oh I see the intention behind this. You'd have to do your own post processing for that at the moment, since  querying for a field that doesn't exist isn't possible _yet_
