### ISSUE TITLE
Where filter does not work

### ISSUE THREAD

**Issue by iaarab** [grahamearley/FirestoreGoogleAppsScript#37]
`else if (isNaN(value)) {
        operator = 'nan'
      }`

always runs even if the value is not a number

**Comment by LaughDonor** [comment]
You're right! Should have probably used [Number.isNaN()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN) instead.

**Comment by grahamearley** [comment]
Good catch — I should have been more thorough in testing that change! I'll fix it ASAP
