### ISSUE TITLE
Missing ARRAY_CONTAINS operator

### ISSUE THREAD

**Issue by joao-azevedo-hydradev** [grahamearley/FirestoreGoogleAppsScript#45]
This operator is missing.

https://firebase.google.com/docs/firestore/reference/rest/v1beta1/StructuredQuery#Operator_1

**Comment by LaughDonor** [comment]
That seems to be a recent addition. Good catch!

**Comment by grahamearley** [comment]
Added with #46, released in [v21](https://github.com/grahamearley/FirestoreGoogleAppsScript/releases/tag/v21)!
