### ISSUE TITLE
readme.md dead link to Google Service Accounts 

### ISSUE THREAD

**Issue by eturk1** [grahamearley/FirestoreGoogleAppsScript#49]
the link in the readme to GSA is a dead link: https://console.developers.google.com/permissions/serviceaccounts

I think this may be the new link: https://console.developers.google.com/projectselector/iam-admin/serviceaccounts?supportedpurview=project&project=&folder=&organizationId=
(found on this Google OAuth page: https://developers.google.com/identity/protocols/OAuth2ServiceAccount)

can't do step #1 on readme.md:
**Quick start**
   Creating a service account
   1. Open the Google Service Accounts page by clicking here.

**Comment by grahamearley** [comment]
Thanks for finding this and providing the updated link! Fixed in commit 06ca121bd33d4071c0f269879005872879ee6ffd

**Comment by eturk1** [comment]
thanks for the quick update!
glad that was the correct link. 

Once I figured out the link, I was able to complete the directions and got a Google Sheet exporting to Firestore last night. thanks a BUNCH for creating this library to help us out!
