### ISSUE TITLE
Document existence

### ISSUE THREAD

**Issue by biodunalfet** [grahamearley/FirestoreGoogleAppsScript#51]
Is there a way to check if a document exists?

**Comment by grahamearley** [comment]
The best way I can think of right now would be to use `getDocument(...)` and see if an error is thrown. It's not super elegant, so we can look into adding some sort of method to encapsulate this.

I don't see any methods in the REST API that can be used for a direct existence check, but I might be missing something. Feel free to check the [REST API reference](https://firebase.google.com/docs/firestore/reference/rest/) or the [API explorer](https://developers.google.com/apis-explorer/#search/firestore/firestore/v1beta1/)!

**Comment by LaughDonor** [comment]
Sounds like a decent workaround. Please comment if there are any major issues, or if a PR is available.
