### ISSUE TITLE
"fields" property

### ISSUE THREAD

**Issue by Biro35** [grahamearley/FirestoreGoogleAppsScript#55]
Is it possible to get the "fields" property without the Firebase types but a JSON object that can be directly updated and passed to updateDocument ?

Thanks

**Comment by grahamearley** [comment]
Yep! If you get a document using `firestore.getDocuments(collectionName)` or `firestore.getDocument(documentPath)`, the `document.fields` property will be a JSON object of the document's fields, without the Firebase types.

**Comment by Biro35** [comment]
Yes, I just noticed it.
Don't remember what I've done to see those Firebase types in a "fields" property.

Thanks again and sorry for this issue.

**Comment by grahamearley** [comment]
No problem! Glad you got it figured out. The raw response from Firestore
includes types, but we remove them for the result we return in this
library.

**Comment by Biro35** [comment]
I think I found where : the "fields" property of the object returned by the "createDocument" function isn't formatted.

**Comment by grahamearley** [comment]
Oh good point! We should always format that result. I'll reopen this issue to track it.

**Comment by Biro35** [comment]
If you set a field with a date, when you get it, it is returned as a string "2019-03-23T23:00:00.000Z" and not as a date object.
