### ISSUE TITLE
Intellisense in IDE

### ISSUE THREAD

**Issue by themcclure** [grahamearley/FirestoreGoogleAppsScript#56]
Distinct from #11, has anyone started on a type/interface file for FirestoreApp and friends?
(in the style of the [Google App Script](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-apps-script/google-apps-script.spreadsheet.d.ts) one)

That seems to be the only way to get intellisense/autocomplete to work in an IDE.

**Comment by piavgh** [comment]
@themcclure : did you manage to solve this?

I'm using Webstorm as my IDE and I also need Intellisense for FirestoreApp

**Comment by themcclure** [comment]
The only solution is for the project to supply a ts interface file. Or to implement your own.

For now, I'm stumbling about with red squiggles and no Intellisense help.

**Comment by LaughDonor** [comment]
This is currently not possible with the current Javascript Engine that Google Apps Script uses. However, once this library is updated to V8, I'm [certain](https://stackoverflow.com/a/33174265/1708751) we'll have this.

**Comment by themcclure** [comment]
That's great news, thanks!

Do you know if existing spreadsheets will be updated to V8 automatically, or will that have to be manually done?

**Comment by LaughDonor** [comment]
Spreadsheets don't use V8, the scripts do. The libraries (like this one) are independent of your code you write in GAS, and they will work together.

**Comment by themcclure** [comment]
OK, I hope so.

I remember the last time the scripting engine was updated and it was a mess on some of the sheets using my GAS code, depending on when the sheet was created... so it gives me pause here.

I presume I'll have to mark the library as using the newer version when it's released, so I can control the release?

**Comment by LaughDonor** [comment]
@themcclure, no action is necessary on your part. When the library is updated to use the V8 engine, you just update your library reference version to it and it will use it.

**Comment by themcclure** [comment]
Best news I've had all day.

Thanks for your work on this!
