### ISSUE TITLE
some param problems

### ISSUE THREAD

**Issue by mnrubin** [grahamearley/FirestoreGoogleAppsScript#57]
- Read.getPage_ has mis-ordered jsdoc params 'request' and 'pageToken'
- Utils.isNumberNaN has type set as param name (ie '{value}' instead of 'value')
- Write.updateDocument_ is missing param name ('mask'), so it uses next word 'if' instead

**Comment by LaughDonor** [comment]
Thanks for the notices! Fixed in [v25](/grahamearley/FirestoreGoogleAppsScript/releases/tag/v25).
