### ISSUE TITLE
Update in nested objects

### ISSUE THREAD

**Issue by vaheg** [grahamearley/FirestoreGoogleAppsScript#58]
https://firebase.google.com/docs/firestore/manage-data/add-data#update_fields_in_nested_objects

does this work with this libary?
haven't been able to do successfully.
Updating only particular value in an object without affecting anything else.

**Comment by stritchi** [comment]
This function is implemented with a mask

          firestore.updateDocument("ab/av", data, mask = true);

https://github.com/grahamearley/FirestoreGoogleAppsScript/releases/tag/v22
