### ISSUE TITLE
Firestore for Google Apps Scripts Production Ready?

### ISSUE THREAD

**Issue by webstermath** [grahamearley/FirestoreGoogleAppsScript#60]
I have several GAS Apps in production that use the [FirebaseApp library](https://github.com/RomainVialard/FirebaseApp) and I would like to start using this library so that I can make use of the new Firestore Database.  I just wanted to ask if anyone else is using this library in production and what their experience is?  Is this library production ready?

**Comment by jgassie** [comment]
I've actually been using FirestoreApp successfully in production for a couple of weeks now... although the library Firestore.js file still has the baseurl defined under v1beta1, I believe the functions exposed in this library haven't changed under Google's Firestore "v1" ... but I haven't tested that on my own at this point under apps script.

**Comment by piavgh** [comment]
@webstermath : I also have this concern. 
By the way, if you know how to listen to realtime update with this library, please share your answer here https://github.com/grahamearley/FirestoreGoogleAppsScript/issues/61.

Thank you.

**Comment by LaughDonor** [comment]
I believe with the upcoming v25 solidifying Collection and Document names and the ability to utilize any REST API version that Google puts out, we can certainly consider this as Production-ready.
