### ISSUE TITLE
Sync firestore with Google Spreadsheets

### ISSUE THREAD

**Issue by viebel** [grahamearley/FirestoreGoogleAppsScript#62]
Can this project be used to sync continuously between hundreds of Google spreadhseets and Firestore. 
I would like to use Firestore as a backend for my data and Spreadsheets to collaborate and visualize and edit the data.

Does it make sense?

**Comment by LaughDonor** [comment]
Yes, though you would have to set up and authenticate your script to be
used across all of them independently.

**Comment by viebel** [comment]
@LaughDonor Can you share some details about how to set up my script and authenticate your script to be used across all of the spreadsheets independently.

My knowledge in Google AppScript is very limited.

**Comment by LaughDonor** [comment]
@viebel, you can use the [Properties Service](
https://developers.google.com/apps-script/guides/properties) to accomplish
this. Store your Firebase credentials on the Script properties level and
that would be shared.

When I said that your script has to be "authenticated independently," I
meant that you need to execute your script on each Spreadsheet first, and
authorize your script to be utilized for that spreadsheet (for security
purposes).

Hope this helps!

**Comment by grahamearley** [comment]
Closing since this seems to be resolved. Feel free to reopen if @LaughDonor's advice didn't answer your question!
