### ISSUE TITLE
"|" character in document name makes it irretrievable

### ISSUE THREAD

**Issue by Fella1990** [grahamearley/FirestoreGoogleAppsScript#63]
Thanks for building this. It's exactly what I needed and nice and simple to use. Great job.

The issue:
I can use createDocument with a custom document name that includes the "|" character
The document appears in the Firebase dashboard

When I use getDocument later, using the exact collection/name format, the response is the same as if the document doesn't exist

Replicated the above without "|", and getDocument was successful

Very minor issue, but perhaps illegal characters could be added to the docs?
It's bad form on my part to use that char, I was just using it while testing for visual separation
I haven't tested if the limitation extends to Collection names

**Comment by LaughDonor** [comment]
Thanks for reporting this. I've been able to update the code to allow all UTF-8 characters to be used. It will be out with [v25](/grahamearley/FirestoreGoogleAppsScript/releases/tag/v25).
