### ISSUE TITLE
How Do I Add A Reference rather than a string value...?

### ISSUE THREAD

**Issue by everythingability** [grahamearley/FirestoreGoogleAppsScript#67]
I've tried...

**Comment by everythingability** [comment]
Oops... I've tried....

/organisations/jfYgO4RnlVQK6JgxYIJp

...and yet it just turns up in the Firebase as a string, like this...

function createDocument( obj ){
 
  var result = firestore.createDocument("users", obj)
  var id = result.name.replace("projects/wibble-wobble/databases/(default)/documents/users/", "")

  Logger.log( id )
    
}
function do_createDocument(){
  var obj = {Name: "Koen Lamberts", Age: 60, Occupation: "VC", organisation:"/organisations/jfYgO4RnlVQK6JgxYIJp"}
  createDocument(obj)
  
}

**Comment by LaughDonor** [comment]
Currently Reference Values are not supported to write to. Perhaps a manual function can be written to convert the string to a reference type?

**Comment by LaughDonor** [comment]
I had another look at this, and I realize that you need to pass the full path to the document. Using your example, the string value should be "projects/wibble-wobble/databases/(default)/documents/organisations/jfYgO4RnlVQK6JgxYIJp".

When strings are wrapped to a value to be sent to Firestore, it tests it against the RegEx `/^projects\/.+?\/databases\/\(default\)\/documents\/(.+\/.+)$/`.
