### ISSUE TITLE
Support for CLASP format

### ISSUE THREAD

**Issue by thesandlord** [grahamearley/FirestoreGoogleAppsScript#7]
Apps Script now supports source control and deployment from the command line. Can we migrate this project to the new CLASP format to enable this?

https://developers.google.com/apps-script/guides/clasp

**Comment by grahamearley** [comment]
Agreed. I've been using [`gapps`](https://github.com/danthareja/node-google-apps-script) but it seems like it might not be supported anymore.

**Comment by grahamearley** [comment]
Done in #10
