### ISSUE TITLE
timestamp fields fail when creating or updating a doc

### ISSUE THREAD

**Issue by Spencer-Easton** [grahamearley/FirestoreGoogleAppsScript#71]
The following code will fail with error:

> Cannot convert firestore.v1.Value with type unset.

```
  db.updateDocument('Timestamps/LastUpdated', {
      lastUpdated: new Date()
    } , true);
```

Currently timestamps are wrapped by: 
```
function wrapDate_ (date) {
        return {'timestampValue': date}
    }
```

I propose the simple addition of toISOString:
```
function wrapDate_ (date) {
        return {'timestampValue': date.toISOString()}
    }
```

**Comment by Xendrez** [comment]
Any chance for getting this in soon?

**Comment by Doomd** [comment]
@Xendrez I had to fork the library and change this line myself. Then I just used my library instead...kind of a pain, but if you're desperate for it to work, it should only take about 10 minutes to set up.

**Comment by Spencer-Easton** [comment]
I also use a fork in my build. Not sure if anyone is actually maintaining this repo.

**Comment by LaughDonor** [comment]
So I finally got around to trying this out myself, and I don't seem to have any issues with the original or the updated code. Not sure if it's because I'm in the same time zone as the Firestore DB. But it checks out.
