### ISSUE TITLE
TypeError: Cannot read property 'getLastRow' of null (line 27, file "Code")

### ISSUE THREAD

**Issue by davidogundepo** [grahamearley/FirestoreGoogleAppsScript#74]
![Screenshot (49)_LI](https://user-images.githubusercontent.com/24846376/76379664-02481280-6351-11ea-9bec-86c9aed51eed.jpg)
![Screenshot (50)_LI](https://user-images.githubusercontent.com/24846376/76379682-0d02a780-6351-11ea-8a1e-134128b656d4.jpg)

Please, what I'm I getting wrong?

**Comment by LaughDonor** [comment]
Could you please show us Line 27? That's where the script is complaining.

**Comment by rielzzapps** [comment]
I think this has nothing to do with the Library, but not having a sheet loaded correctly.

**Comment by sonu-simon** [comment]
I had this issue, and it turned out that I hadn't named the sheet as I mentioned in line number 8. Fixing that solved it for me.

**Comment by LaughDonor** [comment]
Closing for now. If there are more issues, we can reopen.
