### ISSUE TITLE
How to delete a collection

### ISSUE THREAD

**Issue by nidhinkumar06** [grahamearley/FirestoreGoogleAppsScript#76]
Is it possible to delete a collection in firestore using FirestoreGoogleAppsScript

I have tried the below command to delete the document by id

```
 for (var i=0;i<documentIds.length;i++){
      console.log("docu id", documentIds[i]);
      firestore.deleteDocument("timesheet/" + documentIds[i]);
  }
```
may i know is this the only way to delete the record or is there any other way

**Comment by Doomd** [comment]
Probably out of an abundance of caution, there is not a method in the library that allows you to delete an entire collection as this is a non-reversible event that should only happen rarely and after careful consideration. If you do want to delete an entire collection though, it's very easy to do so in the firebase console though: https://youtu.be/nfRUr4nAzyE

**Comment by LaughDonor** [comment]
Firebase has an article about [Deleting Collections and Subcollections](https://firebase.google.com/docs/firestore/solutions/delete-collections). And it begins with:

> Deleting data in Cloud Firestore, especially from a resource-limited mobile app, can be difficult to implement correctly for the following reasons:
> * There is no operation that atomically deletes a collection.
> * Deleting a document does not delete the documents in its subcollections.
> * If your documents have dynamic subcollections, it can be hard to know what data to delete for a given path.
> * Deleting a collection of more than 500 documents requires multiple batched write operations or hundreds of single deletes.
> * In many apps, it isn't appropriate to give end-users permission to delete entire collections.
> 
> Fortunately, you can write a Cloud Function to run safe and performant deletes of entire collections or collection trees.

Your workaround may be the best way to handle this. As I've tried to use wildcards to delete multiple documents.
