### ISSUE TITLE
Make `getPage` method public

### ISSUE THREAD

**Issue by kaladivo** [grahamearley/FirestoreGoogleAppsScript#8]
Please make `getPage` method in Reads.js public so all pages can be fetched.

**Comment by grahamearley** [comment]
As it is, I don't think `getPage` should be made public. I think this library should hide the idea of `pageToken` from the user (open to suggestions on that, though!).

I could see it being useful when using the `get` method, if you want to get all of the pages. What do you think about adding a method called `getAll` that acts like `get` but returns all pages?

While we're on the topic, I think that the `get` method should be removed eventually in favor of more specific methods for getting documents and getting collections of documents (the generic `get` that returns the response should be used privately within the library only, IMO).

**Comment by grahamearley** [comment]
@kaladivo Do you think splitting `get`  into two methods for getting documents and getting collections would solve your problem? What is your use case here?

**Comment by grahamearley** [comment]
I'm going to close this issue because I am not going to make this method public. If you need to use this method in some way that isn't currently possible in the library, please file an issue for that and we can work to make the library work for you.
