### ISSUE TITLE
Doesn't it support non-English property name?

### ISSUE THREAD

**Issue by llitkr** [grahamearley/FirestoreGoogleAppsScript#84]
When I try

firestore.query("collectionName").where("이름", "==", "name"), it makes error "invalid property path "이름"".

Maybe it's because the property name is Korean language.

Is there a way to solve it?

**Comment by LaughDonor** [comment]
@llitkr which version of the library are you using?

**Comment by llitkr** [comment]
@LaughDonor Hello LaughDonor.

I'm tried with last version of library and also tried with code in github. But both of script makes same error.

**Comment by LaughDonor** [comment]
Thanks for this! We need to properly encode the field name by surrounding it with backticks (`).

With version 24 and below, you would modify your query to be like:
```
firestore.query("collectionName").where("`이름`", "==", "name")
```

From version 25 and later, this will be fixed, and the above workaround will not work.

**Comment by LaughDonor** [comment]
Updated with release [v25](/grahamearley/FirestoreGoogleAppsScript/releases/tag/v25).
