### ISSUE TITLE
v25 breaks createDocument when writing to collection

### ISSUE THREAD

**Issue by shoumik1** [grahamearley/FirestoreGoogleAppsScript#85]
Running this `firestore.createDocument("test", data);` where "test" is the name of my collection works perfectly in v24 but in v25 an error occurs. This is the error in question:
`Error: Document name "projects/{project-ID}/databases/(default)/documents/test" lacks "/" at index 54. (line 82, file "Util")`

**Comment by LaughDonor** [comment]
What is the name of your document? Typically, the path would contain it: `collectionName/documentName` or `parentCollection/parentDocument/childCollection/childDocument`

**Comment by shoumik1** [comment]
I'm relying on `createDocument` to autogenerate an ID for my document.

**Comment by LaughDonor** [comment]
Fixed in the published release. Thanks!
