### ISSUE TITLE
firestore.updateDocument(path, data) erase fields

### ISSUE THREAD

**Issue by jbenavv** [grahamearley/FirestoreGoogleAppsScript#89]
Hi, I'm not sure if it's a failure, but when I try to update specific fields, it deletes the ones that already exist.

Before: 
![image](https://user-images.githubusercontent.com/20479508/84691008-0ca61980-af09-11ea-9533-ffb6edd161e0.png)

` var data = {
  "Spaceid": e.space.name,
  "Message": input,
  "Trigger": number,
};`
firestore.updateDocument(path, data);

Later:

![image](https://user-images.githubusercontent.com/20479508/84720897-f1f19600-af44-11ea-8344-ebb07ee31bf8.png)

**Comment by LaughDonor** [comment]
You need to pass a third argument with the value of `true` to not overwrite.

```javascript
var data = { "Spaceid": e.space.name, "Message": input, "Trigger": number, };
firestore.updateDocument(path, data, true);
```

**Comment by jbenavv** [comment]
I found the solution in this case https://github.com/grahamearley/FirestoreGoogleAppsScript/issues/23

Just add a boolean parameter in firestore.updateDocument (path, data, true);

My only suggestion is to add a help example to the new users.

My general opinion as a new user of this library is that it is very good and practical.
