### ISSUE TITLE
[v27] Critical Error: Library with identifier FirestoreApp.GSUnit is missing 

### ISSUE THREAD

**Issue by nathang21** [grahamearley/FirestoreGoogleAppsScript#90]
Looks like GSUnit (a dependency of FirestoreApp) has been modified or is imported in a new way, and I receive the following error when trying to initialize this library on the latest version. I think it should only be using this dependency during build/testing but not as part of the public methods?

I am unable to use v27 of FirestoreApp due to this error:
```
Library with identifier FirestoreApp.GSUnit is missing (perhaps it was deleted, or you don't have read access?)
```

I tried adding GSUnit directly to my dependencies which I found in the source [1] via this libraryID:
`1VXHbMTCarTMcx6H_EHHhaVay4ptnl2I6FjTU8wl0my4ALmM7nLGuZ0WJ`
with no luck, and I also tried this libraryID:
`MIUhnnCDES0N3YHPEWX9DUtkh30YExdAc` [2] of which the official docs point to a different libraryID.

In either case, it looks like this library calls this dependency directly `FirestoreApp.GSUnit` so adding it manually to my dependencies did not help. 

[1] https://script.google.com/a/elitebodysculpture.com/d/1VUSl4b1r1eoNcRWotZM3e87ygkxvXltOgyDZhixqncz9lQ3MjfT1iKFw/edit
[2] https://sites.google.com/site/scriptsexamples/custom-methods/gsunit

**Comment by LaughDonor** [comment]
Thanks for reporting this. Can you check now? I've updated the GSUnit library permissions.

**Comment by nathang21** [comment]
Looks like that did the trick, thanks for the quick fix!
