### ISSUE TITLE
`npm run lint` shows many errors related new line code

### ISSUE THREAD

**Issue by tricknotes** [grahamearley/FirestoreGoogleAppsScript#93]
When I run `$ npm run lint` on my laptop (macOS Catelina 10.15.4), many errors are shown.
Also, when I run `$ npm run fix`, lint replaces all line code to CRLF. 
Like this https://github.com/grahamearley/FirestoreGoogleAppsScript/commit/770e3c1158aaad027e58a9c67375ad3b3cd4d0dd .

Which new line code "\n" ir "\r\n" do you prefer?
I wish lint doesn't show error any environment.

## Minimal code to reproduce the problem
``` sh
$ npm run lint
```

## Expected Behavior
```
(Many errors like the following)
/Users/tricknotes/src/github.com/grahamearley/FirestoreGoogleAppsScript/typings/index.d.ts
   1:53   error  Insert `␍`  prettier/prettier
   2:70   error  Insert `␍`  prettier/prettier
   3:62   error  Insert `␍`  prettier/prettier
   4:27   error  Insert `␍`  prettier/prettier
   5:62   error  Insert `␍`  prettier/prettier
   6:54   error  Insert `␍`  prettier/prettier
   7:1    error  Insert `␍`  prettier/prettier
   8:34   error  Insert `␍`  prettier/prettier
   9:36   error  Insert `␍`  prettier/prettier
  10:35   error  Insert `␍`  prettier/prettier
  11:34   error  Insert `␍`  prettier/prettier
  12:1    error  Insert `␍`  prettier/prettier
  13:45   error  Insert `␍`  prettier/prettier
  14:103  error  Insert `␍`  prettier/prettier
  15:1    error  Insert `␍`  prettier/prettier
  16:66   error  Insert `␍`  prettier/prettier
  17:55   error  Insert `␍`  prettier/prettier
  18:1    error  Insert `␍`  prettier/prettier
  19:66   error  Insert `␍`  prettier/prettier
  20:45   error  Insert `␍`  prettier/prettier

✖ 4709 problems (4709 errors, 0 warnings)
  4709 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firestore_google-apps-script@1.0.30 lint: `eslint --color --ext .ts . && tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firestore_google-apps-script@1.0.30 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tricknotes/.npm/_logs/2020-06-24T03_25_51_289Z-debug.log
```

## Actual Results
There are no lint error .

##### Library Version: 
https://github.com/grahamearley/FirestoreGoogleAppsScript/commit/b7840ac10291f4f8c371b9b0a6aa86179de7d1c4

**Comment by LaughDonor** [comment]
I thought about this during the redesign, and what I noticed is that when pulling the files via. [clasp](/google/clasp), the files come back with `\r\n`, so I did my best to keep that uniform.

You can configure git to respect that on pulling and pushing. [GitHub: Configuring Git to handle line endings](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings)

**Comment by tricknotes** [comment]
> when pulling the files via. [clasp](https://github.com/google/clasp), the files come back with `\r\n`

Ah, thanks for telling me. I didn't know this.

> You can configure git

Surely.
However, many users including me will run lint without such config. (Documentation may help such situation.)

By the way, currently FirestoreGoogleAppsScript uses TypeScript, so there are no chance to pull codes from clasp.
I think we can use `\n` for development, it this right?

**Comment by LaughDonor** [comment]
We could add in a ".gitattributes" file which could enforce this (whichever line endings are utilized).
