### ISSUE TITLE
`firestore.getDocuments()` doesn't return `Document[]` object

### ISSUE THREAD

**Issue by tricknotes** [grahamearley/FirestoreGoogleAppsScript#94]
The return value from `firestore.getDocuments()` doesn't have any getters like `obj`, `created`, and so on.
Is this intentional? If not, I'll try to make a PR to fix this.

## Minimal code to reproduce the problem
```javascript
const firestore = FirestoreApp.getFirestore(email, key, projectId);
const documents = firestore.getDocuments('DocumentPath', ids);
documents[0].obj;
```

## Expected Behavior
``` javascript
documents[0].obj; // This returns raw object.
```

I want to extract a raw object via `document.obj` as it described [here](https://github.com/grahamearley/FirestoreGoogleAppsScript/blame/b7840ac10291f4f8c371b9b0a6aa86179de7d1c4/.github/README.md#L146). 

## Actual Results
``` javascript
documents[0].obj; // undefined
```

##### Library Version: 
[v29](https://github.com/grahamearley/FirestoreGoogleAppsScript/tree/v29)

**Comment by LaughDonor** [comment]
Wow, you're right. The `Document.fields` property is missing altogether when getting back `Document[]`. That's a problem.
