### ISSUE TITLE
Syncing to Sheets but getting values as json in rows with type as key

### ISSUE THREAD

**Issue by Subroid** [grahamearley/FirestoreGoogleAppsScript#97]
## Minimal code to reproduce the problem
```javascript
function importFromFirestore() {

  const firestore = getFirestore();
  const allDocumentsWithMetadata = firestore.getDocuments("Freshtomers");
  
  const allDocuments = allDocumentsWithMetadata.map(function(document) {
    return document.fields;
  });
 
  const firstDocument = allDocuments[0];  
  const columns = Object.keys(firstDocument);
  const vals = Object.values(firstDocument);
  Logger.log(vals);
  const sheet = SpreadsheetApp.getActiveSheet();
  sheet.appendRow(columns);
  
  allDocuments.forEach(function(document) {
    const row = columns.map(function(column) {
      return document[column];
    });
    sheet.appendRow(row);
  });
  
}

```

## Expected Behavior
![image](https://user-images.githubusercontent.com/29721105/86048619-6dd3fe00-ba6e-11ea-8c7c-7c363f4caae2.png)

## Actual Results
![image](https://user-images.githubusercontent.com/29721105/86048387-12a20b80-ba6e-11ea-89fa-778d1c5fe35d.png)

##### Library Version: v32

**Comment by Subroid** [comment]
I've achieved the clean results with library version 26 using the same code

![image](https://user-images.githubusercontent.com/29721105/86051245-bee5f100-ba72-11ea-9b75-65c908f3848f.png)

**Comment by LaughDonor** [comment]
You shouldn't try to directly access the `fields` property of the documents that are returned. Use the `.obj` property of the objects to get the object data.

```javascript
const allDocumentsWithMetadata = firestore.getDocuments("Freshtomers");
const allDocuments = allDocumentsWithMetadata.map(function(document) {
    return document.obj;
});
```

As stated in the [Breaking Changes](/grahamearley/FirestoreGoogleAppsScript#breaking-changes) of **v27**:
> **v27**: All functions return **Document** or **Document[]** types directly from Firebase. Use `document.obj` to extract the raw object.
