### ISSUE TITLE
Extracting collection/document path from document name

### ISSUE THREAD

**Issue by juliusn** [grahamearley/FirestoreGoogleAppsScript#99]
I often find myself in a situation where I have a Firestore document that I want to update or delete, but no other reference to the collection/name than Document.name, which doesn't work as is, so I wrote custom functions to extract these parts from the name string. Is this really necessary? Is there a built-in solution in the library for doing this, or if not, should there be?

```javascript

function pathToRef_(path) {
  return path.match(/(?:[^\/]*\/|^)[^\/]*$/)[0];
}

const docs = fs.getDocuments("collection");

for (const doc in docs) {
  
  const data = {
    "key": value
  }
  
  fs.updateDocument(pathToRef_(docs[doc].name), data, true);
}

```

##### Library Version: 32

**Comment by LaughDonor** [comment]
I'm not sure I'm following accurately... Can you provide an example name and walk through the problem?

We have [`Util_.regexPath`](/grahamearley/FirestoreGoogleAppsScript/blob/773c2371a5931688129b2bae6960c315d1c88a5a/Util.ts#L6) with the expression that is used by the method [`Util_.getDocumentFromPath()`](https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/773c2371a5931688129b2bae6960c315d1c88a5a/Util.ts#L73-75). Does this help at all?

**Comment by juliusn** [comment]
For example if I have a collection of documents and I want to update a common property, calling `updateDocument` like so:

```javascript
const docs = fs.getDocuments("collection");

docs.forEach(doc => fs.updateDocument(doc.name, { "key": "newVal" }, true));
```

throws an error saying `Document name "[...]" lacks "/" at index [...]`. If I want to get a working path for each document, I need to extract it from the `Document.name` property myself using string methods or regex match. I was just wondering if this is really necessary.

**Comment by LaughDonor** [comment]
Oh, I get it. Wouldn't you be able to do:
```javascript
const collectionPath = "collection";
const docs = fs.getDocuments(collectionPath);
docs.forEach(doc => fs.updateDocument(`${collectionPath}/${doc.name}`, { "key": "newVal" }, true));
```

to accomplish the same without the extraction process?

**Comment by juliusn** [comment]
> Oh, I get it. Wouldn't you be able to do:
> 
> ```js
> const collectionPath = "collection";
> const docs = fs.getDocuments(collectionPath);
> docs.forEach(doc => fs.updateDocument(`${collectionPath}/${doc.name}`, { "key": "newVal" }, true));
> ```
> 
> to accomplish the same without the extraction process?

That would create a completely new collection hierarchy under `collection`, because `Document.name` returns with the base path, like `projects/project_id/databases/(default)/collection_name/document_name`.

**Comment by LaughDonor** [comment]
Ok, I'll be adding a property to the `Document` that lets you get this data. In the meantime, you can use:
```javascript
docs.forEach(doc => {
    const name = doc.name.match(/^projects\/.+?\/databases\/\(default\)\/documents\/(.+\/.+)$/)[1];
    fs.updateDocument(`${collectionPath}/${doc.name}`, { "key": "newVal" }, true));
});
````

Where the RegEx is from [`Util_.regexPath`](https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/main/Util.ts#L6).
